name: Sobolev Alignment
description: |
  Sobolev alignment of deep probabilistic models for comparing single cell profiles from pre-clinical models and patients
project_home: https://github.com/NKI-CCB/sobolev_alignment
documentation_home: https://sobolev-alignment.readthedocs.io/
publications:
  - 10.1101/2022.03.08.483431
install:
  pypi: sobolev-alignment
tags:
  - ML
  - deep-generative-models
  - kernel-methods
  - pre-clinical
  - clinical
  - scrnaseq
license: MIT
version: 1.0.0
authors:
  - saroudant
test_command: |
  pip install ."[dev]" && pytest
